//
//  LandingItem.swift
//  Todo App
//
//  Created Blankz on 28/1/2564 BE.
//  Copyright © 2564 BE Blank. All rights reserved.
//
//  Template generated by Blankz
//

import Foundation

struct LandingItem {
    enum View {
        case name
        case age
        case email
        case password
    }
    
    struct Request {
        let isLogin: Bool
        let name: String
        let age: String
        let email: String
        let password: String
    }
    
    struct Reponse: Codable {
        let token: String
    }
}
