//
//  TodoDetailInteractor.swift
//  Todo App
//
//  Created Blankz on 30/1/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Blankz
//

import UIKit

class TodoDetailInteractor: TodoDetailInteractorInputProtocol {

    weak var presenter: TodoDetailInteractorOutputProtocol?
    
    func updateTodo(from form: TodoDetailItem.Request.UpdateTodo) {
        var parameter = [String: Any]()
        if let description = form.description {
            parameter["description"] = description
        }
        
        if let isCompleted = form.isCompleted {
            parameter["completed"] = isCompleted
        }

        Loading.shared.show()
        Service.shared.requestData(httpMethod: .put,
                                   link: .task(form.id),
                                   parameter: parameter) { response in
            Loading.shared.hide()
            switch response {
            case .success(let data):
                do {
                    let responseTodo = try JSONDecoder().decode(TodoDetailItem.Response.Update.self,
                                                                from: data)
                    self.presenter?.didReceive(todoItem: responseTodo)
                } catch let error {
                    self.presenter?.didReceive(Error: error.localizedDescription)
                }
            case .failure(let message):
                self.presenter?.didReceive(Error: message)
            }
        }

    }
}
