//
//  TodoDetailRouter.swift
//  Todo App
//
//  Created Blankz on 30/1/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Blankz
//

import UIKit

class TodoDetailRouter: TodoDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func presentTodoDetail(from view: AnyObject,
                                  todoItem: TodoItem) {
        guard let sourceView = view as? UIViewController else { return }
        
        let view = TodoDetailViewController()
        let interactor = TodoDetailInteractor()
        let router = TodoDetailRouter()
        let presenter = TodoDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        presenter.todoItem = todoItem
        presenter.delegate = (sourceView as? TodoListViewController)?.presenter as? TodoListDelegate

        sourceView.navigationController?.pushViewController(view, animated: true)
    }
}
