//
//  TodoDetailItem.swift
//  Todo App
//
//  Created Blankz on 30/1/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Blankz
//

import Foundation

struct TodoDetailItem {
    struct Request {
        struct UpdateTodo {
            let id: String
            var description: String?
            var isCompleted: Bool?
        }
    }
    
    struct Response {
        struct Update: Decodable {
            let todo: TodoItem
        
            private enum RootKey: String, CodingKey {
                case data
            }

            init(from decoder: Decoder) throws {
                let root = try decoder.container(keyedBy: RootKey.self)
                todo = try root.decode(TodoItem.self, forKey: .data)
            }
        }
    }
}
