//
//  TodoListRouter.swift
//  Todo App
//
//  Created Blankz on 30/1/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Blankz
//

import UIKit

class TodoListRouter: TodoListWireframeProtocol {
    weak var viewController: UIViewController?
    static func createModule() -> UINavigationController {
        
        let view = TodoListViewController()
        let interactor = TodoListInteractor()
        let router = TodoListRouter()
        let presenter = TodoListPresenter(interface: view,
                                          interactor: interactor,
                                          router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        let navigationController = UINavigationController(rootViewController: view)
        navigationController.navigationBar.isTranslucent = false
        return navigationController
    }
    
    func presentToDoDetail(todoItem: TodoItem) {
        TodoDetailRouter.presentTodoDetail(from: viewController!,
                                           todoItem: todoItem)
    }
    
    func presentLanding() {
        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
        let landingView = LandingRouter.createModule()
        
        if #available(iOS 13.0, *) {
            if let scene = UIApplication.shared.connectedScenes.first {
                guard let windowScene = (scene as? UIWindowScene) else { return }
            
                let window: UIWindow = UIWindow(frame: windowScene.coordinateSpace.bounds)
                window.windowScene = windowScene //Make sure to do this
                window.rootViewController = landingView
                window.makeKeyAndVisible()
                appDelegate.window = window
            }
        } else {
            appDelegate.window?.rootViewController = landingView
            appDelegate.window?.makeKeyAndVisible()
        }
    }
}
